#!/bin/bash

error()
{
if [ "$?" != "0" ]; then
kill $(ps aux | grep -m 1 'AFP Servers' | awk 'BEGIN { FS = " " } ; { print $2 }') &>2
exit 1
fi
}

case $1 in
	--version	)	echo "Version 3.0"; exit 0 ;;
	-v		)	echo "Version 3.0"; exit 0 ;;
esac

if [ -z "$(systemctl status avahi-daemon.service | grep inactive)" ]; then
        echo "Avahi Already Running"
else
gksudo daemon avahi-daemon start
error
fi

if [ -z "$( ps -e | grep afpfsd )" ]; then
	running=False
else
	running=True
fi
space=" "
if [ "$running" == "True" ]; then
	unmntfield='--field=Unmount All:CHK' 
fi

avahi-browse -rkt  _afpovertcp._tcp | grep -v IPv4 > /tmp/net
slist=$(cat /tmp/net | grep -o [0-9][0-9][0-9].[0-9][0-9][0-9].*.*[0-9])
array=($slist)
if [ -z $(echo ${array[*]} | sed s/" "/#/g) ]; then
	svlist="No Servers"
else
	svlist=$(echo ${array[*]} | sed s/" "/#/g)
fi
yad --text-info --title="AFP Servers" --geometry=250x700+10+30 --filename=/tmp/net &
error
input=$(yad --title="AFP Server Info" --form --center --item-separator=# --separator=: \
	--field=Username  \
	--field=Password:H \
	--field=Server:CBE \
	--field=Volume \
	--field="Mount Point":DIR "Username" "Password" "$svlist" "Macintosh HD" "$unmntfield"
 )
error
user=$( echo $input | awk 'BEGIN { FS = ":" } ; { print $1 }' )
pass=$( echo $input | awk 'BEGIN { FS = ":" } ; { print $2 }' )
srv=$( echo $input | awk 'BEGIN { FS = ":" } ; { print $3 }' )
vol=$( echo $input | awk 'BEGIN { FS = ":" } ; { print $4 }' )
mnt=$( echo $input | awk 'BEGIN { FS = ":" } ; { print $5 }' )
unmount=$( echo $input | awk 'BEGIN { FS = ":" } ; { print $6 }' )

if [ "$unmount" == "TRUE" ]; then
	afp_client exit | yad --title 'AFP Exit' --text-info --center --width 350 --height 400
else
	afp_client mount -u "$user" -p "$pass" "$svr":"$vol" "$mnt" | yad --text-info --center --auto-close --height 100 --width 300
fi

kill $(ps aux | grep -m 1 'AFP Servers' | awk 'BEGIN { FS = " " } ; { print $2 }')
