#!/bin/bash

error()
{
if [ "$?" != "0" ]; then
kill $(ps aux | grep -m 1 'Select Services' | awk 'BEGIN { FS = " " } ; { print $2 }') &>2
kill $(ps aux | grep -m 1 'daemondialog' | grep bash | awk 'BEGIN { FS = " " } ; { print $2 }') &>2
exit 1
fi
}

# get status of services
if [ -n "$( systemctl status nfsd.service | grep inactive)" ]; then
	nfscstat=False
else
	nfscstat=True
fi

if [ -n "$( systemctl status rpc-idmapd.service | grep inactive)" ]; then
	nfsvstat=False
else
	nfsvstat=True
fi
	
if [ -n "$(systemctl status smbd.service | grep inactive)" ]; then
	smbstat="False"
else
	smbstat="True"
fi

if [ -n "$(systemctl status sshd.service | grep inactive)" ]; then
	sshstat="False"
else
	sshstat="True"
fi

if [ -n "$(systemctl status cupsd.service | grep inactive)" ]; then
	cupsstat="False"
else
	cupsstat="True"
fi

if [ -n "$(systemctl status avahi-daemon.service | grep inactive)" ]; then
	avahistat="False"
else
	avahistat="True"
fi

if [ -n "$(systemctl status bluetooth.service | grep inactive)" ]; then
	bluestat="False"
else
	bluestat="True"
fi

if [ -n "$(systemctl status x11vnc.service | grep inactive)" ]; then
	x11srvstat="False"
else
	x11srvstat="True"
fi
# create window
input=$(yad --width=500 --height=300 --list \
	  --separator=" " \
          --title="Select Services" \
          --column="Status" --column="Service" --column="Description" \
	  --print-column=2 \
	  --hide-column=2 \
	  --center \
	  --checklist \
	    $nfscstat "nfs-common" "Network File Sharing Client Service" \
            $nfsvstat "nfs-server" "Network File Sharing Server" \
            $smbstat "samba" "Windows File Server" \
	    $sshstat "ssh" "Secure Shell Server" \
	    $cupsstat "cups" "Printing Services" \
	    $avahistat "avahi" "AVAHI DNS Daemon" \
	    $bluestat "bluetoothd" "Bluetooth Daemon"\
	    $x11srvstat "x11srv" "X11 VNC Server")
error
nc=0
ns=0
smb=0
sshs=0
cups=0
avahi=0
blue=0
x11srv=0

for i in $input ; do
	case $i in
	nfs-common	)	nc=1; [ $nfscstat == True ] || gksudo systemctl start nfsd.service; error ;;
	nfs-server	)	ns=1; [ $nfsvstat == True ] || gksudo systemctl start idmapd.service start; gksudo systemctl start mountd.service;error ;;
	samba		)	smb=1; [ $smbstat == True ] || gksudo systemctl start smbd.service; error ;;
	ssh		)	sshs=1; [ $sshstat == True ] || gksudo systemctl start sshd; error ;;
	cups		)	cups=1; [ $cupsstat == True ] || gksudo systemctl start cupsd.service; error ;;
	avahi		)	avahi=1; [ $avahistat == True ] || gksudo systemctl start avahi-daemon.service; error ;;
	bluetoothd	)	blue=1; [ $bluestat == True ] || gksudo systemctl start bluetooth.service start; error; blueman-applet;;
	x11srv		)	x11srv=1; [ $x11srvstat == True ] || gksudo systemctl start x11vnc.servicer start; error;
	
	esac
done

[ $nc == 1 ] || [ $nfscstat == False ] || gksudo systemctl stop nfsd.service
error
[ $ns == 1 ] || [ $nfsvstat == False ] || gksudo systemctl stop idmapd.service && gksudo systemctl stop mountd.service
error
[ $smb == 1 ] || [ $smbstat == False ] || gksudo systemctl stop smbd.service
error
[ $sshs == 1 ] || [ $sshstat == False ] || gksudo systemctl stop sshd.service
error
[ $cups == 1 ] || [ $cupsstat == False ] || gksudo systemctl stop cupsd
error
[ $avahi == 1 ] || [ $avahistat == False ] || gksudo systemctl stop avahi-daemon.service
error
[ $blue == 1 ] || [ $bluestat == False ] || gksudo systemctl stop bluetooth.service
error
[ $x11srv == 1 ] || [ $x11srvstat == False ] || gksudo systemctl stop x11vnc.service
